### ISSUE TITLE
Previous package!!!

### ISSUE THREAD

**Issue by LucaJeevanjee** [lohQ/NTmU_mobile#1]
Hi sorry to bring up an issue on this repo, but I was wondering if you have access to the `virgil-flutter-e3-kit-extended` repo you have seem to have deleted as I was using it in a project and its no longer available.

If you do have it, think you could upload it again so I can use it as a package, or send me the project as a zip so i can have it in my own repo.

Thanks in advance.

**Comment by lohQ** [comment]
Just saw this issue! I thought there's nobody using it so just changed the visibility to private. 

Can share it with you if you are still interested in the repo!

**Comment by LucaJeevanjee** [comment]
> Just saw this issue! I thought there's nobody using it so just changed the visibility to private. 
> 
> Can share it with you if you are still interested in the repo! 
> 

Thanks for the reply, managed to dig it up from my pubdev cache luckily. I've found your package is the only one to work on flutter 👍🏾

**Comment by lohQ** [comment]
Glad that it is helpful to you :)

**Comment by LucaJeevanjee** [comment]
Hey sorry to bother you again,
I'm getting ```java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.virgilsecurity.sdk.storage.DefaultKeyStorage$Entries.containsKey(java.lang.Object)' on a null object reference``` with the package sometimes which causes a crash and requires me to clear my storage. Any ideas why?

**Comment by lohQ** [comment]
It has been quite some time since I last worked on Android projects, so... nope, no idea why :')

**Comment by LucaJeevanjee** [comment]
Ah no problem, pretty rare anyways, I think it's to do with hot restarting too many times and it mixing up the cache.
